CREATE TABLE USERS (
  USERNAME VARCHAR(25) NOT NULL,
  PASSWORD VARCHAR(64) NOT NULL,
  EMAIL VARCHAR(80) NOT NULL,
  TYPE INT NOT NULL,
  PRIMARY KEY (EMAIL)
);

CREATE TABLE COURSES (
  COURSE_ID SERIAL, -- Auto incrementing type
  COURSE_NAME VARCHAR(150) NOT NULL,
  EMAIL VARCHAR(80) NOT NULL,
  SEMESTER VARCHAR(80) NOT NULL,
  YEAR INT NOT NULL,
  PRIMARY KEY (COURSE_ID),
  FOREIGN KEY (EMAIL) REFERENCES USERS (EMAIL)
);

CREATE TABLE FORMS (
  FORM_ID SERIAL,
  COURSE_ID INT NOT NULL,
  OUTCOME VARCHAR (80) NOT NULL,
  DATA JSON NOT NULL,
  -- FILE
  PRIMARY KEY (FORM_ID),
  FOREIGN KEY (COURSE_ID) REFERENCES COURSES (COURSE_ID)
);

CREATE TABLE FILES (
  FILE_ID INT NOT NULL,
  FILE_NAME VARCHAR(100) NOT NULL,
  FORM_ID INT NOT NULL,
  -- FILE
  PRIMARY KEY (FILE_ID),
  FOREIGN KEY (FORM_ID) REFERENCES FORMS (FORM_ID)
);
